spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ams_db?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: cuonglhfpt
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: create

server:
  port: 8888

app:
  security:
    secret-key: 4GNADCBiQKBIb3DQEBAQUAA4GNADCBiQKBgQCPqVE4GNADCBi